# Generated by Django 3.1.3 on 2021-06-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210608_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_content',
            field=models.CharField(max_length=200),
        ),
    ]
